<?php
declare(strict_types=1);

header('Content-Type: application/json');

require __DIR__ . '/db.php';

// ---- 1. Read and validate the request body ----
$body = json_decode(file_get_contents('php://input'), true);

$userId = $body['user_id'] ?? null;

if (!$userId) {
    http_response_code(400);
    echo json_encode(['error' => 'user_id is required']);
    exit;
}

// ---- 2. Find this user's open session (the opposite check of clock-in.php) ----
$stmt = $pdo->prepare(
    'SELECT id FROM attendance_logs WHERE user_id = ? AND clock_out_time IS NULL'
);
$stmt->execute([$userId]);
$openSession = $stmt->fetch();

if (!$openSession) {
    http_response_code(409);
    echo json_encode(['error' => 'No open clock-in found — clock in first']);
    exit;
}

// ---- 3. Close it out. NOW() is generated by MySQL, never by the phone. ----
$ipAddress = $_SERVER['REMOTE_ADDR'] ?? null;

$stmt = $pdo->prepare(
    'UPDATE attendance_logs SET clock_out_time = NOW(), clock_out_ip = ? WHERE id = ?'
);
$stmt->execute([$ipAddress, $openSession['id']]);

echo json_encode(['success' => true, 'clocked_out_at' => date('Y-m-d H:i:s')]);
