<?php
declare(strict_types=1);

header('Content-Type: application/json');

require __DIR__ . '/db.php';       // gives us $pdo
require __DIR__ . '/config.php';   // SALON_LAT, SALON_LNG, ALLOWED_RADIUS_METERS
require __DIR__ . '/distance.php'; // distanceInMeters()

// ---- 1. Read and validate the request body ----
$body = json_decode(file_get_contents('php://input'), true);

$userId = $body['user_id'] ?? null;
$lat    = $body['latitude'] ?? null;
$lng    = $body['longitude'] ?? null;

if (!$userId || $lat === null || $lng === null) {
    http_response_code(400);
    echo json_encode(['error' => 'user_id, latitude, and longitude are required']);
    exit;
}

// ---- 2. Verify the staff member is actually near the salon ----
// This check happens on the server, using coordinates the phone sent.
// Never trust a client-side "I'm close enough" boolean — that can be
// spoofed by anyone with devtools open, which defeats the whole point.
$distance = distanceInMeters((float) $lat, (float) $lng, SALON_LAT, SALON_LNG);

if ($distance > ALLOWED_RADIUS_METERS) {
    http_response_code(403);
    echo json_encode([
        'error'           => 'Too far from the salon to clock in',
        'distance_meters' => round($distance),
    ]);
    exit;
}

// ---- 3. Make sure they don't already have an open clock-in ----
$stmt = $pdo->prepare(
    'SELECT id FROM attendance_logs WHERE user_id = ? AND clock_out_time IS NULL'
);
$stmt->execute([$userId]);

if ($stmt->fetch()) {
    http_response_code(409);
    echo json_encode(['error' => 'Already clocked in — clock out first']);
    exit;
}

// ---- 4. Insert the log. NOW() is generated by MySQL, never by the phone. ----
// $_SERVER['REMOTE_ADDR'] is set by Apache itself from the actual network
// connection — the phone can't fake this the way it could fake a value sent
// in the request body, since it's not something the client controls at all.
$ipAddress = $_SERVER['REMOTE_ADDR'] ?? null;

$stmt = $pdo->prepare(
    'INSERT INTO attendance_logs (user_id, clock_in_time, latitude, longitude, ip_address)
     VALUES (?, NOW(), ?, ?, ?)'
);
$stmt->execute([$userId, $lat, $lng, $ipAddress]);

echo json_encode(['success' => true, 'clocked_in_at' => date('Y-m-d H:i:s')]);
